In [9]:
from array import array

import numpy as np

vector = np.random.randn(128)
print(vector)

matrix_3d = np.tile(vector, (3, 3, 1))
new_matrix_3d = np.random.randn(3,3,128)
re = np.einsum("ijk,imn->ijm",new_matrix_3d, matrix_3d )

[-1.35715757  0.35331805  0.4691832  -1.56256746  0.32866212  1.28615348
 -0.41393254  1.11940997 -0.48019466  1.51176555  0.85378006  1.99756795
  0.24226245  0.58780194  1.12809734 -1.20889823 -0.54701069  2.02090498
  0.1257599  -2.8563607  -0.24248895  0.13624091 -0.82979611  1.43934321
  1.37370448 -1.4177893  -1.75027769  0.58204018  0.619901   -0.70236039
  0.36935988 -0.13528249 -0.0055211  -0.39080352  0.22903524  0.49225487
  2.04603631 -0.0654398   0.85412551 -0.85629865 -0.40455773 -1.51254704
 -0.41385335  0.17566554  0.0357697  -0.40495249 -0.78833306 -0.28518123
 -0.88573149  0.54394661  0.18217971  0.39745685  0.57262293  1.05976981
  0.09159046 -0.40074259  1.03124477 -1.63553363 -0.13238212  0.46648099
 -1.52865743 -0.89622001  0.46600284 -0.68260766 -0.80504729  0.33406077
 -1.1977844   0.04855241 -0.18473335  1.26225156  0.47881384  1.11512597
  1.15720563 -0.45841978  0.31482295  0.42325151 -0.0246934  -1.02056201
 -0.41109435 -1.08532731 -0.35625596  0.87812086  0

In [11]:
# 假设你有一个二维数组
your_2d_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [10, 11, 12]])

# 定义一个包含你想要提取的行索引的列表
row_indices = [3, 2]  # 假设你想要提取第1行和第3行

# 使用高级索引提取这些行
selected_rows = your_2d_array[row_indices]

print(selected_rows)

[[10 11 12]
 [ 7  8  9]]


In [79]:
import numpy as np

def find_orthogonal_unit_vector(u):
    # 确保u是一个numpy数组
    u = np.array(u)
    # 生成一个随机的128维向量
    v = np.random.rand(128)
    # 标准化v
    v = v / np.linalg.norm(v)
    # 计算v在u上的投影
    projection = np.dot(v, u) * u
    # 从v中减去投影，得到正交向量
    v_orthogonal = v - projection
    # 标准化正交向量
    v_orthogonal = v_orthogonal / np.linalg.norm(v_orthogonal)
    return v_orthogonal

# 假设给定的单位向量是 given_unit_vector
given_unit_vector = np.random.rand(128)
given_unit_vector = given_unit_vector / np.linalg.norm(given_unit_vector)  # 标准化

# 生成正交单位向量
orthogonal_unit_vector = find_orthogonal_unit_vector(given_unit_vector)
print(orthogonal_unit_vector @ given_unit_vector)
np.linalg.norm(orthogonal_unit_vector)

1.3877787807814457e-17


1.0

In [82]:
16*256*256

1048576

In [11]:
import numpy as np

# 定义向量和矩阵
vector = np.array([[1, 2]])
matrix = np.array([[[1,2],[1,2]], [[1,3],[1,3]], [[2,3],[1,3]]])

# 使用np.tensordot进行点乘
result = np.tensordot(vector, matrix, axes=([1],[2]))[0][2]

print(result.shape)

(2,)


In [13]:
def check_elements_existence(elements, reference_set):
    # 将列表转换为集合，以便进行快速成员检测
    elements_set = set(elements)
    # 使用集合的交集操作来检查至少有一个元素是否存在
    return not elements_set.isdisjoint(reference_set)

# 示例使用
reference_list = ['dog', 'cat', 'giraffe', 'fly', 'mosquito']
reference_set = set(reference_list)  # 将列表转换为集合

# 要检查的元素列表
elements_to_check = ['do' ]

# 调用函数并打印结果
result = check_elements_existence(elements_to_check, reference_set)
print(result)  # 如果至少有一个元素存在于参考集合中，打印True，否则打印False

False


In [3]:
import faiss
import numpy as np


d = 128  # 向量维度
nb = 10000000  # 数据库中的向量数量
nq = 10  # 查询向量数量

# 生成随机的数据库向量
xb = np.random.random((nb, d)).astype('float32')
# 生成随机的查询向量
xq = np.random.random((nq, d)).astype('float32')

# 2. 创建IndexLSH索引
n_bits = 64  # 哈希位数
index = faiss.IndexLSH(d, n_bits)
index.add(xb)  # 添加数据库向量




In [10]:
# 5. 执行搜索
k = 50  # 返回最近邻的数量
D, I = index.search(xq, k)  # D是距离，I是索引

# 6. 输出结果
print("查询向量的最近邻索引:\n", I)


print("查询向量的最近邻距离:\n", D)

查询向量的最近邻索引:
 [[7238801  951045 8945591 4706835 1974474 7294035 7981129 9759238 8249335
  1439064 7514616 1650486 5367573 8317808 9131198 1229052 7199037 1379111
    71660  913400 6758681  185856 4821183  785991 5765556 4526369 4407139
  5233547 8235020 5394262 8833350 3598474 7162488 4231055 3438818 7622709
  7895535 2712211 6137133 4274663 3003899 2700562 1849456 1787316  345179
  1907547 1626864  349604 1561957 1567600]
 [9466163 6202733 8832883 2521792 3631723 7262134 6483986  885335 5141470
  4800823 3802359   49140 8156000 7909632 6569749 6999191 5747167 5607856
  3836153   45225 2799606  496471   23390 3541702 2515847  374014 1003000
  8385598 7661531 8409616  183931 6950887 6266460 1820635  816976 5939517
  5352229 5942223 4537802 4652350 8883831 1989595   14107  472323 3091931
  3093006 8891712 1632962 2489703 1797205]
 [3582472 3082687 4490299 9220803 9863385 3886417 6343079 5967277 2244767
  9922950 5091742 3682641  505020   99928 8493247 4587206 1264634 3416626
  3352139  47

In [25]:
np.random.seed(0)
d = 64  # 向量维度
nb = 100000  # 数据库的大小
nq = 10  # 查询向量的数量

# 生成随机向量
xb = np.random.random((nb, d)).astype('float32')
xq = np.random.random((nq, d)).astype('float32')

# 创建HNSW索引
index = faiss.IndexHNSWFlat(d, 32)  # 32是HNSW的M参数，表示层数

# 训练HNSW索引
index.hnsw.efConstruction = 200  # 用于构建的候选邻居数
index.add(xb)

In [26]:

k = 50  # 返回最近邻的数量
D, I = index.search(xq, k)  # D是距离，I是索引

# 6. 输出结果
print("查询向量的最近邻索引:\n", I)

print("查询向量的最近邻距离:\n", D)

查询向量的最近邻索引:
 [[ 9163 82911 49631 22830 87855 18257 25676 58646 48146 46472 29802 35524
  24001 43003 97486 53011 96803 30119 80507 29909 81428 39096 57929 55768
  52931 11521 57868 76826 14960 75030 94196 83390 89177 75501 87445 45793
  85432 41589 65557 91342 84015 49247 74623 49835 73747 91935 87775 61338
  76091  3971]
 [24760 61236 82094 78297 91934 83860 95826 42041 27045 43055 22377 60719
  77059 31151 23295 59844 94963 57049 65593 57777 37903 22352 47727 91629
  73671  3476 55790 93567 25441  5421 45578 27681 70365 35696 59317 67568
  43932 48640 90343 33011 26206 63342 90628  6375 43770 36245 65805 66198
  48432 66904]
 [27276  9749 67673  3495 51614 32520 89967 17089 62202 63094 91822 32237
  12054  8570 75961 73193 16214 32659 25118 10077 76195 58989 89066 35695
  27896 68298 87557 83570 50816 64017 18275 38119 92514 24093 45722 38164
  41597 11492 68183 36950 79342 82094 51876 94062  4451 41199 92096  8382
  11399 75400]
 [93188 27296 55989 40171 27632 84998 11859 84018 7489

In [28]:
import faiss

# 设置参数配置
nb = 1000000  # 数据库中的数据量
nq = 10000    # 查询向量的数量
nlist = 100  # 聚类中心的数量
nprobe = 10  # 搜索时考虑的聚类中心数量
d = 64       # 向量维度
m = 16       # 子量化器的数量
nbits = 8    # 每个码字的位数

# 准备测试样本集和训练集
def CreateDataSet(nb, nq, d):
    np.random.seed(1234)
    xb = np.random.random((nb, d)).astype('float32')
    xb[:, 0] += np.arange(nb) / 1000.
    xq = np.random.random((nq, d)).astype('float32')
    xq[:, 0] += np.arange(nq) / 1000.
    return xb, xq

xb, xq = CreateDataSet(nb, nq, d)

# 创建 IVFPQ 索引实例
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFPQ(quantizer, d, nlist, m, nbits)

# 训练索引
index.train(xb)

# 添加数据库向量
index.add(xb)

In [30]:
k = 10  # 要返回的最近邻个数
D, I = index.search(xq, k)
print("查询向量的最近邻索引:\n", I)

print("查询向量的最近邻距离:\n", D)


查询向量的最近邻索引:
 [[   13   175    66 ...   479   817   530]
 [  969   547   375 ...   225   379   207]
 [  460   142   744 ...   740   306   637]
 ...
 [ 9229 10896  9510 ... 10026  9914 10602]
 [10584  9725 10905 ... 10611  8871 11091]
 [ 9464 10164 10199 ...  9779  9465 10215]]
查询向量的最近邻距离:
 [[6.089201  6.4078093 6.792976  ... 6.985145  6.999053  7.0156813]
 [6.5274134 6.618491  6.6720943 ... 7.1723003 7.1893005 7.2152424]
 [7.404247  7.4941607 7.539292  ... 8.0674715 8.074457  8.087131 ]
 ...
 [6.70463   6.770023  7.185424  ... 7.6795993 7.687398  7.7319613]
 [6.6065865 7.195006  7.3886504 ... 7.6989627 7.7096567 7.746282 ]
 [6.569078  6.989082  7.0611773 ... 7.45152   7.5362687 7.5435686]]


In [32]:
faiss.write_index(index, '/home/chunming/data/chunming/projects/LSHMultivector/notebook/large.index')